# Generated by Django 4.2.4 on 2023-08-26 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Appuser',
        ),
    ]
