# Generated by Django 4.1.7 on 2023-08-27 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_appuser_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appuser',
        ),
    ]
